### ISSUE TITLE
When the player moves through a line to defeat the enemies, the enemies that should've been defeated still kills the player.

### ISSUE THREAD

**Issue by josejovian** [rickyxyz/cutter#1]
Is this intentional?

**Comment by rickyxyz** [comment]
<img width="97" alt="Screenshot 2022-05-17 161119" src="https://user-images.githubusercontent.com/56119701/168751120-a1a2035e-aef1-427c-9856-7801dc09ba8d.png">

Probably issue with either the hitbox or the game loop.

**Comment by rickyxyz** [comment]
Bug fixed on commit [1bcd540](https://github.com/rickyxyz/cutter/commit/1bcd540e3db0ae11e88b2eca1be4b0be83bd3d26) by adding hitbox on player during player movement.
